# Generated by Django 4.2.11 on 2026-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={},
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_user",
        ),
        migrations.AddField(
            model_name="message",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_crisis",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(default="user", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="vector_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
