# Generated by Django 4.2.11 on 2026-04-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_journalentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="remedy_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
