# Generated by Django 4.2.11 on 2026-04-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_journalentry_remedy_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together=set(),
        ),
    ]
