# Generated by Django 4.2.11 on 2026-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_ai_insight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_remedy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
